
export const VIEW_EMPLOYEE_DATA = "FETCH_EMPLOYEE_DATA";
export const ADD_EMPLOYEE_DATA = "ADD_EMPLOYEE_DATA";
export const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA";
export const UPDATE_EMPLOYEE_DATA = "UPDATE_EMPLOYEE_DATA";

